//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Search.orkin.Landingpages.RollinsLeadProcessClient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Leads", Namespace="http://schemas.datacontract.org/2004/07/Rollins.LandingPages.WebAPI.Helper")]
    [System.SerializableAttribute()]
    public partial class Leads : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInfo_LeadAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInfo_LeadAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AdditionalInfo_LeadAddressIsOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInfo_LeadCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInfo_LeadPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string AdditionalInfo_LeadStateOrProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CrmIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField10Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField3Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField4Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField5Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField6Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField7Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField8Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomField9Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadAdditionalDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadAddress1Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadAddress2Field;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LeadAddressIsOwnedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadCityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadCommentsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadCompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LeadCreationDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadEmailAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadFirstNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LeadIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadIndustryNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadJobTitleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadKeywordsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadLastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadOriginationDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadPostalCodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadPreferredContactMethodField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadPrimaryPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadReferrerDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<System.DateTime> LeadRequestedAppointmentDateTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadRuleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int LeadRuleIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadSecondaryPhoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LeadStateOrProvinceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool LeadWantsSolicitationsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MarketingCampaignIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Xml.Linq.XElement MarketingCampaignXmlSnapshotField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PestsCsvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceGroupIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ServiceLinesCsvField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SubmittedMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime TimestampField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string isSameAsServiceAddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo_LeadAddress1 {
            get {
                return this.AdditionalInfo_LeadAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfo_LeadAddress1Field, value) != true)) {
                    this.AdditionalInfo_LeadAddress1Field = value;
                    this.RaisePropertyChanged("AdditionalInfo_LeadAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo_LeadAddress2 {
            get {
                return this.AdditionalInfo_LeadAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfo_LeadAddress2Field, value) != true)) {
                    this.AdditionalInfo_LeadAddress2Field = value;
                    this.RaisePropertyChanged("AdditionalInfo_LeadAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AdditionalInfo_LeadAddressIsOwned {
            get {
                return this.AdditionalInfo_LeadAddressIsOwnedField;
            }
            set {
                if ((this.AdditionalInfo_LeadAddressIsOwnedField.Equals(value) != true)) {
                    this.AdditionalInfo_LeadAddressIsOwnedField = value;
                    this.RaisePropertyChanged("AdditionalInfo_LeadAddressIsOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo_LeadCity {
            get {
                return this.AdditionalInfo_LeadCityField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfo_LeadCityField, value) != true)) {
                    this.AdditionalInfo_LeadCityField = value;
                    this.RaisePropertyChanged("AdditionalInfo_LeadCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo_LeadPostalCode {
            get {
                return this.AdditionalInfo_LeadPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfo_LeadPostalCodeField, value) != true)) {
                    this.AdditionalInfo_LeadPostalCodeField = value;
                    this.RaisePropertyChanged("AdditionalInfo_LeadPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AdditionalInfo_LeadStateOrProvince {
            get {
                return this.AdditionalInfo_LeadStateOrProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.AdditionalInfo_LeadStateOrProvinceField, value) != true)) {
                    this.AdditionalInfo_LeadStateOrProvinceField = value;
                    this.RaisePropertyChanged("AdditionalInfo_LeadStateOrProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CrmId {
            get {
                return this.CrmIdField;
            }
            set {
                if ((object.ReferenceEquals(this.CrmIdField, value) != true)) {
                    this.CrmIdField = value;
                    this.RaisePropertyChanged("CrmId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField1 {
            get {
                return this.CustomField1Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField1Field, value) != true)) {
                    this.CustomField1Field = value;
                    this.RaisePropertyChanged("CustomField1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField10 {
            get {
                return this.CustomField10Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField10Field, value) != true)) {
                    this.CustomField10Field = value;
                    this.RaisePropertyChanged("CustomField10");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField2 {
            get {
                return this.CustomField2Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField2Field, value) != true)) {
                    this.CustomField2Field = value;
                    this.RaisePropertyChanged("CustomField2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField3 {
            get {
                return this.CustomField3Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField3Field, value) != true)) {
                    this.CustomField3Field = value;
                    this.RaisePropertyChanged("CustomField3");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField4 {
            get {
                return this.CustomField4Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField4Field, value) != true)) {
                    this.CustomField4Field = value;
                    this.RaisePropertyChanged("CustomField4");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField5 {
            get {
                return this.CustomField5Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField5Field, value) != true)) {
                    this.CustomField5Field = value;
                    this.RaisePropertyChanged("CustomField5");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField6 {
            get {
                return this.CustomField6Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField6Field, value) != true)) {
                    this.CustomField6Field = value;
                    this.RaisePropertyChanged("CustomField6");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField7 {
            get {
                return this.CustomField7Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField7Field, value) != true)) {
                    this.CustomField7Field = value;
                    this.RaisePropertyChanged("CustomField7");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField8 {
            get {
                return this.CustomField8Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField8Field, value) != true)) {
                    this.CustomField8Field = value;
                    this.RaisePropertyChanged("CustomField8");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomField9 {
            get {
                return this.CustomField9Field;
            }
            set {
                if ((object.ReferenceEquals(this.CustomField9Field, value) != true)) {
                    this.CustomField9Field = value;
                    this.RaisePropertyChanged("CustomField9");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadAdditionalData {
            get {
                return this.LeadAdditionalDataField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadAdditionalDataField, value) != true)) {
                    this.LeadAdditionalDataField = value;
                    this.RaisePropertyChanged("LeadAdditionalData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadAddress1 {
            get {
                return this.LeadAddress1Field;
            }
            set {
                if ((object.ReferenceEquals(this.LeadAddress1Field, value) != true)) {
                    this.LeadAddress1Field = value;
                    this.RaisePropertyChanged("LeadAddress1");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadAddress2 {
            get {
                return this.LeadAddress2Field;
            }
            set {
                if ((object.ReferenceEquals(this.LeadAddress2Field, value) != true)) {
                    this.LeadAddress2Field = value;
                    this.RaisePropertyChanged("LeadAddress2");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LeadAddressIsOwned {
            get {
                return this.LeadAddressIsOwnedField;
            }
            set {
                if ((this.LeadAddressIsOwnedField.Equals(value) != true)) {
                    this.LeadAddressIsOwnedField = value;
                    this.RaisePropertyChanged("LeadAddressIsOwned");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadCity {
            get {
                return this.LeadCityField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadCityField, value) != true)) {
                    this.LeadCityField = value;
                    this.RaisePropertyChanged("LeadCity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadComments {
            get {
                return this.LeadCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadCommentsField, value) != true)) {
                    this.LeadCommentsField = value;
                    this.RaisePropertyChanged("LeadComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadCompanyName {
            get {
                return this.LeadCompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadCompanyNameField, value) != true)) {
                    this.LeadCompanyNameField = value;
                    this.RaisePropertyChanged("LeadCompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LeadCreationDateTime {
            get {
                return this.LeadCreationDateTimeField;
            }
            set {
                if ((this.LeadCreationDateTimeField.Equals(value) != true)) {
                    this.LeadCreationDateTimeField = value;
                    this.RaisePropertyChanged("LeadCreationDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadEmailAddress {
            get {
                return this.LeadEmailAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadEmailAddressField, value) != true)) {
                    this.LeadEmailAddressField = value;
                    this.RaisePropertyChanged("LeadEmailAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadFirstName {
            get {
                return this.LeadFirstNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadFirstNameField, value) != true)) {
                    this.LeadFirstNameField = value;
                    this.RaisePropertyChanged("LeadFirstName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LeadId {
            get {
                return this.LeadIdField;
            }
            set {
                if ((this.LeadIdField.Equals(value) != true)) {
                    this.LeadIdField = value;
                    this.RaisePropertyChanged("LeadId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadIndustryName {
            get {
                return this.LeadIndustryNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadIndustryNameField, value) != true)) {
                    this.LeadIndustryNameField = value;
                    this.RaisePropertyChanged("LeadIndustryName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadJobTitle {
            get {
                return this.LeadJobTitleField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadJobTitleField, value) != true)) {
                    this.LeadJobTitleField = value;
                    this.RaisePropertyChanged("LeadJobTitle");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadKeywords {
            get {
                return this.LeadKeywordsField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadKeywordsField, value) != true)) {
                    this.LeadKeywordsField = value;
                    this.RaisePropertyChanged("LeadKeywords");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadLastName {
            get {
                return this.LeadLastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadLastNameField, value) != true)) {
                    this.LeadLastNameField = value;
                    this.RaisePropertyChanged("LeadLastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadOriginationData {
            get {
                return this.LeadOriginationDataField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadOriginationDataField, value) != true)) {
                    this.LeadOriginationDataField = value;
                    this.RaisePropertyChanged("LeadOriginationData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadPostalCode {
            get {
                return this.LeadPostalCodeField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadPostalCodeField, value) != true)) {
                    this.LeadPostalCodeField = value;
                    this.RaisePropertyChanged("LeadPostalCode");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadPreferredContactMethod {
            get {
                return this.LeadPreferredContactMethodField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadPreferredContactMethodField, value) != true)) {
                    this.LeadPreferredContactMethodField = value;
                    this.RaisePropertyChanged("LeadPreferredContactMethod");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadPrimaryPhone {
            get {
                return this.LeadPrimaryPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadPrimaryPhoneField, value) != true)) {
                    this.LeadPrimaryPhoneField = value;
                    this.RaisePropertyChanged("LeadPrimaryPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadReferrerData {
            get {
                return this.LeadReferrerDataField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadReferrerDataField, value) != true)) {
                    this.LeadReferrerDataField = value;
                    this.RaisePropertyChanged("LeadReferrerData");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> LeadRequestedAppointmentDateTime {
            get {
                return this.LeadRequestedAppointmentDateTimeField;
            }
            set {
                if ((this.LeadRequestedAppointmentDateTimeField.Equals(value) != true)) {
                    this.LeadRequestedAppointmentDateTimeField = value;
                    this.RaisePropertyChanged("LeadRequestedAppointmentDateTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadRule {
            get {
                return this.LeadRuleField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadRuleField, value) != true)) {
                    this.LeadRuleField = value;
                    this.RaisePropertyChanged("LeadRule");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int LeadRuleId {
            get {
                return this.LeadRuleIdField;
            }
            set {
                if ((this.LeadRuleIdField.Equals(value) != true)) {
                    this.LeadRuleIdField = value;
                    this.RaisePropertyChanged("LeadRuleId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadSecondaryPhone {
            get {
                return this.LeadSecondaryPhoneField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadSecondaryPhoneField, value) != true)) {
                    this.LeadSecondaryPhoneField = value;
                    this.RaisePropertyChanged("LeadSecondaryPhone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LeadStateOrProvince {
            get {
                return this.LeadStateOrProvinceField;
            }
            set {
                if ((object.ReferenceEquals(this.LeadStateOrProvinceField, value) != true)) {
                    this.LeadStateOrProvinceField = value;
                    this.RaisePropertyChanged("LeadStateOrProvince");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool LeadWantsSolicitations {
            get {
                return this.LeadWantsSolicitationsField;
            }
            set {
                if ((this.LeadWantsSolicitationsField.Equals(value) != true)) {
                    this.LeadWantsSolicitationsField = value;
                    this.RaisePropertyChanged("LeadWantsSolicitations");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MarketingCampaignId {
            get {
                return this.MarketingCampaignIdField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketingCampaignIdField, value) != true)) {
                    this.MarketingCampaignIdField = value;
                    this.RaisePropertyChanged("MarketingCampaignId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Xml.Linq.XElement MarketingCampaignXmlSnapshot {
            get {
                return this.MarketingCampaignXmlSnapshotField;
            }
            set {
                if ((object.ReferenceEquals(this.MarketingCampaignXmlSnapshotField, value) != true)) {
                    this.MarketingCampaignXmlSnapshotField = value;
                    this.RaisePropertyChanged("MarketingCampaignXmlSnapshot");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PestsCsv {
            get {
                return this.PestsCsvField;
            }
            set {
                if ((object.ReferenceEquals(this.PestsCsvField, value) != true)) {
                    this.PestsCsvField = value;
                    this.RaisePropertyChanged("PestsCsv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceGroupId {
            get {
                return this.ServiceGroupIdField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceGroupIdField, value) != true)) {
                    this.ServiceGroupIdField = value;
                    this.RaisePropertyChanged("ServiceGroupId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ServiceLinesCsv {
            get {
                return this.ServiceLinesCsvField;
            }
            set {
                if ((object.ReferenceEquals(this.ServiceLinesCsvField, value) != true)) {
                    this.ServiceLinesCsvField = value;
                    this.RaisePropertyChanged("ServiceLinesCsv");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubmittedMessage {
            get {
                return this.SubmittedMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.SubmittedMessageField, value) != true)) {
                    this.SubmittedMessageField = value;
                    this.RaisePropertyChanged("SubmittedMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime Timestamp {
            get {
                return this.TimestampField;
            }
            set {
                if ((this.TimestampField.Equals(value) != true)) {
                    this.TimestampField = value;
                    this.RaisePropertyChanged("Timestamp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string isSameAsServiceAddress {
            get {
                return this.isSameAsServiceAddressField;
            }
            set {
                if ((object.ReferenceEquals(this.isSameAsServiceAddressField, value) != true)) {
                    this.isSameAsServiceAddressField = value;
                    this.RaisePropertyChanged("isSameAsServiceAddress");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RollinsLeadProcessClient.IRollins")]
    public interface IRollins {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollins/LeadSubmission", ReplyAction="http://tempuri.org/IRollins/LeadSubmissionResponse")]
        Search.orkin.Landingpages.RollinsLeadProcessClient.Leads LeadSubmission(Search.orkin.Landingpages.RollinsLeadProcessClient.Leads objLeadsRequest);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRollins/LeadSubmission", ReplyAction="http://tempuri.org/IRollins/LeadSubmissionResponse")]
        System.Threading.Tasks.Task<Search.orkin.Landingpages.RollinsLeadProcessClient.Leads> LeadSubmissionAsync(Search.orkin.Landingpages.RollinsLeadProcessClient.Leads objLeadsRequest);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IRollinsChannel : Search.orkin.Landingpages.RollinsLeadProcessClient.IRollins, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RollinsClient : System.ServiceModel.ClientBase<Search.orkin.Landingpages.RollinsLeadProcessClient.IRollins>, Search.orkin.Landingpages.RollinsLeadProcessClient.IRollins {
        
        public RollinsClient() {
        }
        
        public RollinsClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RollinsClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RollinsClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RollinsClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Search.orkin.Landingpages.RollinsLeadProcessClient.Leads LeadSubmission(Search.orkin.Landingpages.RollinsLeadProcessClient.Leads objLeadsRequest) {
            return base.Channel.LeadSubmission(objLeadsRequest);
        }
        
        public System.Threading.Tasks.Task<Search.orkin.Landingpages.RollinsLeadProcessClient.Leads> LeadSubmissionAsync(Search.orkin.Landingpages.RollinsLeadProcessClient.Leads objLeadsRequest) {
            return base.Channel.LeadSubmissionAsync(objLeadsRequest);
        }
    }
}
